function [] = hsInitializeSkillGroupWithName(fileID, GroupName)

% Create a generic group name to place everything that is generated by this
% code in a manageable group within the layout window.

% Author: Haris Suhail, UCLA

CMD = sprintf('groupId = dbCreateFigGroup(cv "%s" nil ''(0 0) "R0")\n',GroupName);
%CMD_STRING_1 = ['groupId = dbCreateFigGroup(cv "',GroupName,'" nil '];
%CMD_STRING_2 ='(0 0) "R0")\n';
%fprintf(fileID,CMD_STRING_1);
%fprintf(fileID,"'");
%fprintf(fileID,CMD_STRING_2);
fprintf(fileID,CMD);
end
