function [] = hsInitializeSkillFile(fileID)
% Create a generic group name to place everything that is generated by this
% code in a manageable group within the layout window.

% Author: Haris Suhail, UCLA

fprintf(fileID, 'GroupName = "SKILL_GROUP_TOP_ROUTE"\n');
fprintf(fileID, 'let( (cv) \n');
fprintf(fileID, 'cv = geGetEditCellView() \n');
hsInitializeSkillGroup(fileID);
hsInitializeViaTechFile(fileID);
end

