function [] = hsInitializeSkillFileWithGroupName(fileID, GroupName)
% Create a generic group name to place everything that is generated by this
% code in a manageable group within the layout window.

% Author: Haris Suhail, UCLA

%fprintf(fileID, ['GroupName = "',GroupName,'"\n']);
CMD = sprintf('GroupName="%s"\n',GroupName);
fprintf(fileID, CMD);
%fprintf(fileID, 'let( (cv) \n');
fprintf(fileID, 'cv = geGetEditCellView() \n');
hsInitializeSkillGroupWithName(fileID, GroupName);
hsInitializeViaTechFile(fileID);
end

