function [] = hsInitializeSkillGroup(fileID)
% Create a generic group name to place everything that is generated by this
% code in a manageable group within the layout window.

% Author: Haris Suhail, UCLA

CMD_STRING_1 = 'groupId = dbCreateFigGroup(cv "SKILL_GROUP_TOP_ROUTE" nil ';
CMD_STRING_2 ='(0 0) "R0")\n';
fprintf(fileID,CMD_STRING_1);
fprintf(fileID,"'");
fprintf(fileID,CMD_STRING_2);
end
